### PR TITLE
Feature: mandatory keys - required() method

### PR DESCRIPTION
**Pull request by wturyn**
Feature requested in issue: https://github.com/indexzero/nconf/issues/128

### CODE REVIEW

**Comment by moberemk** [comment]
@indexzero any chance of this getting merged in? I've been looking for this exact behaviour.

**Comment by indexzero** [comment]
Yes. This is a very clean feature. Just behind on PR review.

**Comment by indexzero** [comment]
@moberemk could you make a PR with docs for this?

**Comment by moberemk** [comment]
Not my feature originally but sure, I've got a little time today to throw something together.

**Pull request merged**
