### PR TITLE
Argv store separator

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Support a separator option for the argv store as it exists for the env.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@mhamann conflict resolved

**Comment by AdrieanKhisbe** [comment]
by next-minor, do you intend 0.10 I guess?

**Comment by mhamann** [comment]
Yeah, thinking about cherry-picking a few commits for a 0.10.0 while working on 1.0

**Comment by AdrieanKhisbe** [comment]
@mhamann cool!
What do you expect to embark? And do you think it will happen soon?
(If you need help, just tell me :))

**Comment by mhamann** [comment]
Initial thoughts are that 0.10 would drop late this coming week or early the following.

**Comment by AdrieanKhisbe** [comment]
@mhamann 
cool, configue major can wait for it. :)

**Comment by mhamann** [comment]
@AdrieanKhisbe v0.10 published

**Comment by AdrieanKhisbe** [comment]
@mhamann that's awesome!!!!! 🎉

**Pull request merged**
