### PR TITLE
added safe constructor for nconf

### LINKED ISSUE #142: Dependencies using nconf reset configuration
I'm trying to use the [node-zendesk]() package in my application. Turns out that because node-zendesk also uses nconf, my nconf values are deleted by node-zendesk's usage of `nconf.env()` and `nconf.defaults()`.

Is there a way to have dependencies have their own instance of nconf that won't conflict with my applications version. Is there something wrong in node-zendesk's usage of nconf? https://github.com/blakmatrix/node-zendesk/blob/b7de2319ce82d76d5296dbf1855af9e6a447d0e5/lib/client.js#L21-L58

### PR DESCRIPTION
**Pull request by qfox**
Fixes #142

### CODE REVIEW

**Comment by zxqfox** [comment]
Guys, do you interested in this PR?

cc @indexzero @jcrugzz

**Comment by jcrugzz** [comment]
@zxqfox sorry for a late reply, this has definitely been in thought. This would be a breaking change and we arent quite ready for it yet. For anyone seeing this, use `new nconf.Provider()` until we get this resolved.

**Comment by johnsonw** [comment]
Thanks for the response, this worked for me :+1:

**Comment by mhamann** [comment]
@zxqfox I see some good benefits by merging this in the near future, but it needs tests and updates to the documentation. Any interest in helping out by adding those items to this PR?

**Comment by zxqfox** [comment]
Docs definitely.

What tests we need for this?

**Comment by zxqfox** [comment]
Not sure I can do more. Feel free to pick it up

**Pull request closed without merging**
