### PR TITLE
Don't pollute process.env with lowerCase opt. Add camelCase opt.

### PR DESCRIPTION
**Pull request by fobos**
So, first of all I think that pollute process.env is very bad idea in 2 reasons:
1. Environment config should be immutable as fact. We should change vars only in `nconf` innstance
2. After pollution automatically we manipulate with conf that 2 times bigger than before.

Added `camelCase` option that overrides `lowerCase` option and converts all keys to camel case notation.

It also fixes https://github.com/indexzero/nconf/pull/189

@indexzero What you think?

Tomorrow I'm gonna fix and add some test and write some examples.

### CODE REVIEW

**Comment by fobos** [comment]
@indexzero @jcrugzz I have fixed and updated my PR. Could you please review it and give a feedback to me.

**Comment by Diokuz** [comment]
+1

**Comment by AdrieanKhisbe** [comment]
@fobos Should it be closed with #211?

**Comment by fobos** [comment]
@AdrieanKhisbe No it shouldn't. As you see I'm also adding `camelCase` option and covering it by tests.

**Comment by fobos** [comment]
Also #211 looks a bit ugly because it reassign declared`env` variable. I think such code is hard to maintain and potentially buggy. Why just don't use `map` instead?

**Comment by AdrieanKhisbe** [comment]
@fobos I have read too fast the title and missed the CamelCase part. My bad :)

**Comment by fobos** [comment]
@AdrieanKhisbe what do you think about `camelCase` option?  If it's ok, I can  rebase the PR and resolve conflicts to update.

**Comment by AdrieanKhisbe** [comment]
I think it could be a good feature:
though I don't know why you made `this.lowerCase = options.camelCase || options.lowerCase || false;`?
Also I would see a test ensuring that there is no pollution of the process.env

**Comment by fobos** [comment]
Ok, I will review my PR to restore context. I made it more than ear ago.

**Comment by mhamann** [comment]
I believe the mutation of `process.env` was fixed with #211.

As far as a camelCasing option goes, it seems like a pretty specific use case. I'm thinking it could be better handled by #199, where you can pass your own `transform` function into a provider (which could be used to convert `camel_case` to `camelCase`.

Any additional feedback, @fobos?

**Comment by fobos** [comment]
Just closed this PR because it is too old.

**Pull request closed without merging**
