### PR TITLE
Update yargs dependency

### PR DESCRIPTION
**Pull request by josephpage**
Related #180

Tests ok locally.

### CODE REVIEW

**Comment by josephpage** [comment]
Travis logs : 
```
$ nvm install 0.8
Version '0.8' not found - try `nvm ls-remote` to browse available versions.
```
```
$ nvm install 0.11
Version '0.11' not found - try `nvm ls-remote` to browse available versions.
```
wtf ?    Will try again in a few hours.

**Comment by 3rd-Eden** [comment]
Maybe try running travis ci on their new arch by setting `sudo: false` in the `.travis.yml`

**Comment by josephpage** [comment]
Yes @3rd-Eden, maybe. It's already waiting for merging : #169

**Comment by josephpage** [comment]
#171 is merged and all dependencies are now up to date.
Thanks @ChristianMurphy

**Pull request closed without merging**
