### PR TITLE
Passing a custom Yargs to Nconf

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Add posibility to pass a yargs instance to argv() method

Follow up on #202 with tests

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
(for some strange reason, had to made the conflict resolve twice)

**Comment by mhamann** [comment]
Weird. Did a rebase not work?

**Comment by AdrieanKhisbe** [comment]
i didn't rebase.
I could do so hence removing the merge commit

**Comment by mhamann** [comment]
I think rebasing would be good if you don't mind.

**Comment by AdrieanKhisbe** [comment]
so be it

**Comment by AdrieanKhisbe** [comment]
@mhamann voilà :)
it's done

**Comment by mhamann** [comment]
Superb! Merged.

**Comment by AdrieanKhisbe** [comment]
cool!
@mhamann Do you want a hand about the other PR that needs tests?

**Comment by mhamann** [comment]
@AdrieanKhisbe that would be a huge help if you have the time. If I were to do it, it might get done this weekend, but not sure if I will end up having enough time to complete or not.

This is the one: https://github.com/indexzero/nconf/pull/247

**Pull request merged**
