### PR TITLE
Improved CI

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Some tweaks to improve the CI :)

- add node v5 to tested version
- Set up cover test with istanbul 
  - update travis accordingly
  - add coveralls ci support
  - add badge to README

see : 
- travis status : 
- coveralls status: https://coveralls.io/github/AdrieanKhisbe/nconf

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
> $ touch @indexzero :smiley:

**Comment by indexzero** [comment]
@AdrieanKhisbe this looks great, but I'm new to coveralls. Is it configured using Github OAuth? i.e. can I access / configure it myself?

**Comment by AdrieanKhisbe** [comment]
indeed it use github oauth. :smiley: 
 You just have to login to coveralls to activate covering using your github account. (the same ways than travis).
Then at each push, travis build will send coverage reports.

**Comment by AdrieanKhisbe** [comment]
> $ touch this :)

**Comment by indexzero** [comment]
Let's see if it works. I think I setup Coveralls correctly.

**Pull request merged**
