### PR TITLE
enable use with webpack by removing unnecessary fs call

### LINKED ISSUE #130: Support using nconf in a (browserify-based) browser context
Hi.

Like [StackOverflow post "using nconf in the browser"](http://stackoverflow.com/questions/27297709/using-nconf-in-the-browser), I'm trying to use your package in a browserify setup, but because nconf calls `fs.readdirSync` when it is `require()`d to scan directories for configuration, it fails in the browser.

→ Is it something that sounds feasible with nconf, or do you suggest going for another package / custom solution?

Thanks for the help, and sorry for posting this as an issue, it's more of a question to which _"we do not and will not support that"_ can be a fine answer.

### PR DESCRIPTION
**Pull request by evoye**
to fix #130 this pull request takes the code from an old but forgotten branch https://github.com/indexzero/nconf/commit/d501e7b04ce0c04b950f94ca8b7d31d26e50fc61

### CODE REVIEW

**Comment by smartin015** [comment]
Could this get checked in please? I'm running into  the same bug.

**Comment by brandones** [comment]
When's the next release planned for? I need this.

**Comment by mhamann** [comment]
This is already released in v0.8.5

**Comment by dkent600** [comment]
I'm using v0.10.0 and the problem still exists.

"TypeError: existsSync is not a function"

**Comment by mhamann** [comment]
I think this is occurring due to some dependencies required by `yargs`. In v1.0, we'll upgrade to the latest version, which may help.

**Comment by catamphetamine** [comment]
> I think this is occurring due to some dependencies required by `yargs`. In v1.0, we'll upgrade to the latest version, which may help.

This does look like an issue in `yargs`

```
Can't import the named export 'dirname' from non EcmaScript module (only default export is available)
...
 @ c:/dev/JITU/node_modules/yargs/build/index.cjs
 @ c:/dev/JITU/node_modules/yargs/index.cjs
 @ c:/dev/JITU/node_modules/nconf/lib/nconf/stores/argv.js
 @ c:/dev/JITU/node_modules/nconf/lib/nconf/stores sync ^\.\/.*$
 @ c:/dev/JITU/node_modules/nconf/lib/nconf.js
 @ c:/dev/JITU/node_modules/node-zendesk/lib/client.js
 @ c:/dev/JITU/lib/zendesk.js
 ```

**Pull request merged**
