### PR TITLE
Migrating test to jest

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Here is the response to #282 Migrating all the test to Jest

I adapted a bit the structure of the test suites, merging it at some place.

Maybe a pass on the title to adapt them could be useful, but I'll like input on current status before to do further actions.

### CODE REVIEW

**Comment by mhamann** [comment]
@AdrieanKhisbe this looks good. can you rebase and see why that Node v4 build is failing? Then we'll get it all merged up. Thanks so much for tackling!

**Comment by AdrieanKhisbe** [comment]
@mhamann Still interested? :)
Prefer to check before to make the rebase

**Comment by mhamann** [comment]
Yes, for sure @AdrieanKhisbe.

We have a problem right now where the TravisCI build for this repo no longer seems to run and I don't have admin access to fix it. :-(

So that's gumming up the works presently.

**Comment by AdrieanKhisbe** [comment]
test are running on my repo: https://travis-ci.org/AdrieanKhisbe/nconf

**Comment by mhamann** [comment]
@AdrieanKhisbe looks good to me. anything else missing / needed?

**Comment by AdrieanKhisbe** [comment]
@mhamann I don't think so :)

**Comment by mhamann** [comment]
Thanks! Here we go!

**Pull request merged**
