### PR TITLE
Add tests for node 0.12 and io.js

### PR DESCRIPTION
**Pull request by josephpage**
Because node 0.12 is cool ! :smile:

### CODE REVIEW

**Comment by josephpage** [comment]
This test doesn't pass. Need help
https://github.com/indexzero/nconf/blob/master/test/hierarchy-test.js#L79

```
When using nconf configured with .argv(), .file() and invoked with nested command line options
    ✗ should merge nested objects 
 
SyntaxError: Unexpected end of input 
      at Object.parse (native) 
      at Object.vows.describe.addBatch.When using nconf.configured with .argv(), .file() and invoked with nested command line options.should merge nested objects  (/home/travis/build/indexzero/nconf/test/hierarchy-test.js:98:31) 
      at runTest (/home/travis/build/indexzero/nconf/node_modules/vows/lib/vows.js:136:26) 
      at EventEmitter.<anonymous> (/home/travis/build/indexzero/nconf/node_modules/vows/lib/vows.js:81:9) 
      at EventEmitter.emit (events.js:129:20) 
      at EventEmitter.options.Emitter.emit (/home/travis/build/indexzero/nconf/node_modules/vows/lib/vows.js:241:24) 
      at that.emitter.ctx (/home/travis/build/indexzero/nconf/node_modules/vows/lib/vows/context.js:32:52) 
      at Object.env.callback (/home/travis/build/indexzero/nconf/node_modules/vows/lib/vows/context.js:46:29) 
      at ChildProcess.<anonymous> (/home/travis/build/indexzero/nconf/test/hierarchy-test.js:94:16) 
      at ChildProcess.emit (events.js:110:17)
```

**Comment by Oza94** [comment]
I havn't looked at the source code for the test and implementation but node 0.12 mainly focus on buffers (which are not used by nconf). 

I think you should dig on [vows](http://vowsjs.org/) which is the test runner, not tested on node 0.12 and not really maintained/active since 7 months. Also you can check locally with node .12 to see if it fails, it may be a non reproductible bug from travis.

By the way, adding iojs to the CI would be very great since the node/io merge will use io as the basis

**Comment by Oza94** [comment]
The test seems to random-fail, I've looked into the source and here is what I found:

 * The error is triggered because of an invalid JSON being parsed [here](https://github.com/indexzero/nconf/blob/d335b5a0f511db5123414c41e9e35b708c1a781a/test/hierarchy-test.js#L98)
 * This JSON is generated from a [child process](https://github.com/indexzero/nconf/blob/d335b5a0f511db5123414c41e9e35b708c1a781a/test/hierarchy-test.js#L87) which spawn [this script](https://github.com/indexzero/nconf/blob/master/test/fixtures/scripts/nconf-hierarchical-load-merge.js), the test spawn it and then listen to stdout to get the JSON string

Here is my supposition:

 * The feature is not broken only the test
 * For whatever reason the test receive the `exit` event before it has received all the JSON string (on `data` event)
 * The test blow up because the JSON is then invalid

This is for me what can better explain the "randomness" of this issue.

What is strange:

 * Child Process API has [no breaking changes](https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12#child-process) in 0.12
 * [Another test](https://github.com/indexzero/nconf/blob/d335b5a0f511db5123414c41e9e35b708c1a781a/test/hierarchy-test.js#L59) just above the one which fails seems to use the same method without any issue

Maybe be adding a `setTimeout` or `setImmediate` at the end of `nconf-hierarchical-load-merge.js` will help, I'm really not sure... Anyway hope this will help and we'll get ride of the issue.

**Comment by Oza94** [comment]
Okay I'm pretty sure the problem is related to what I've said in my last message.
When you look at `exit` [event](https://nodejs.org/api/child_process.html#child_process_event_exit) documentation in node:

> Note that the child process stdio streams might still be open.

What is strange is that this is not a new behavior for node 0.12. @josephpage I think you should listen on [`close` event](https://nodejs.org/api/child_process.html#child_process_event_close) on the spawned process since:

> This event is emitted when the stdio streams of a child process have all terminated.

@ChristianMurphy this is probably why the tests on #171 failed.

**Comment by josephpage** [comment]
Rebase done

**Comment by josephpage** [comment]
up @jcrugzz

**Comment by josephpage** [comment]
@ChristianMurphy In order to accelerate the merge by maintainers, I purpose to integrate your changes from #169 ?

I will also modify `before_install` like this, [as recommended on npm wiki](https://github.com/npm/npm/wiki/Troubleshooting#travis-projects-using-08-cant-upgrade-to-npm-2) :

``` 
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
```

Any thoughts ?

**Comment by ChristianMurphy** [comment]
Sure, feel free to merge that branch into this one. :+1: 
As for the npm update, go for it, that should allow the `^` operator purposed in #171  to work properly on node 0.8 :smile:

**Comment by josephpage** [comment]
Merged #169

**Pull request merged**
