### PR TITLE
Added support for saving configuration to a specific file

### PR DESCRIPTION
**Pull request by yxliang01**
Added support for saving configuration to a specific file. Solving #229, #218.

### CODE REVIEW

**Comment by yxliang01** [comment]
Cool! Thanks. Will this be included in a new version to be uploaded to `npm`? Initially, I thought this project is dead since lots of PR and issues were pending to be processed for almost a year. It would be great if new versions can be uploaded to `npm`. That way, I don't have to create a new `npm` package for my fork.

Thanks

**Comment by AdrieanKhisbe** [comment]
I don't know, I juste had a look on some of PR as I am restarting to work on my library configue that builds up on top of nconf.

Maybe we should contact @indexzero

**Comment by ralekna** [comment]
+1

**Comment by yxliang01** [comment]
Cool. Hope this can be in the new release of the `nconf` package on `npm` soon. I really don't like to create my fork...

**Comment by mhamann** [comment]
@yxliang01 I am working on merging this, but it needs tests before it will be accepted.

If I have time, I will eventually get around to adding tests for this, but you can expedite the process by providing tests for us. :-)

**Comment by yxliang01** [comment]
Hello @mhamann , same I will write tests when I am available, but it might not be happening soon... Busy working on other stuff at the moment.

**Comment by mhamann** [comment]
Resolved via #283.

**Comment by linqFR** [comment]
> Resolved via #283.

is it?

**Pull request closed without merging**
